### ISSUE TITLE
CryptoHopper Webhook not working 

### ISSUE THREAD

**Issue by REFLEXGAMING007** [soranoo/TradingView-Free-Webhook-Alerts#36]
**the bug**
I tried with both Webhook.site & CryptoHopper but only the CryptoHopper's webhook not working. Its showing 
Send webhook failed.
Reason: Too many requests. Please try again later.
Status: 429

**To Reproduce**
Just send anything to this webhook "https://www.cryptohopper.com/tradingview_alerts/hook?key=gRV4L83dwOPp3YlWwmRtA6BzN3cpixO6pL9lN8YWmM6MejCbjPETMJ0WlBpsn7FC"

**Screenshots**
![Screenshot_20230412-083501230.jpg](https://user-images.githubusercontent.com/56241882/231339200-fe368e94-2d29-4e64-94f9-670a35af7bd5.jpg)

** Environment:**
 - Program Version: [cloud-pipdream]

**Comment by soranoo** [comment]
This is not a bug, the error means the CryptoHopper server refuses your request since your rate limit has been hit.

CryptoHopper seems to have a harsh rate limit.

> Our API has a request rate limit to provide an equal share of our bandwidth resources to all of our users. Our current rate limits are 2 request per second per user, except when it comes to placing buy orders. In that case, the maximum amount of buy orders that can be placed is one order each 8 seconds.

I have added a new feature to the Local version to make the system retry the request automatically after a certain time if the `Retry-After` header is found in the response.  **BUT** I am sorry that the feature is not available in the cloud version now. ~~I am no idea why pipdream cannot run the time.sleep correctly.~~

Ref: https://www.cryptohopper.com/api-documentation/how-the-api-works
